#  <-- tasks file can include smaller files if warranted

- name: check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: install EPEL repo.
  shell: yum install -y "{{ epel_repo_url }}"
  when: not epel_repofile_result.stat.exists
 
#- name: install EPEL repo.
#  yum:
#    name: "{{ epel_repo_url }}"
#    state: present
#  register: result
#  when: not epel_repofile_result.stat.exists

- name: import EPEL GPG key.
  shell: rpm --import "{{ epel_repo_gpg_key_url }}"
  when: not epel_repofile_result.stat.exists

#- name: import EPEL GPG key.
#  rpm_key:
#    key: "{{ epel_repo_gpg_key_url }}"
#    state: present
#  when: not epel_repofile_result.stat.exists

- name: yum epel-release
  shell: yum install -y epel-release
  ignore_errors: yes

- name: set rhui-REGION-rhel-server-releases.skip_if_unavailable=true
  shell: yum-config-manager --save --setopt=rhui-REGION-rhel-server-releases.skip_if_unavailable=true

- name: install the 'Server with GUI' package group
  yum:
    name: "@^Server with GUI"
    state: present
    skip_broken: yes

#- name: install the 'Server with GUI' package group
#  shell: yum groupinstall -y "Server with GUI" --skip-broken

- name: downgrade xorg-x11-server-Xorg 1.19.3-11.el7_4.2
  yum:
    name: xorg-x11-server-Xorg-1.19.3-11.el7_4.2
    allow_downgrade: yes

- name: install the latest version of xrdp
  yum:
    name: xrdp
    state: latest
    skip_broken: yes

- name: install 1.8.0-2.el7_4 of tigervnc-server
  yum:
    name: tigervnc-server-1.8.0-2.el7_4
    state: present

- name: add exclude xorg-x11-server-Xorg,tigervnc-server to yum.conf
  lineinfile:
    dest: /etc/yum.conf
    state: present
    regexp: "^exclude=.*$"
    insertafter: EOF
    line: "exclude=xorg-x11-server-Xorg,tigervnc-server"

- name: disabled firewalld
  systemd:
    name: firewalld
    enabled: no
    daemon_reload: yes

- name: stop firewalld
  systemd:
    name: firewalld
    state: stopped
    daemon_reload: yes

- name: start xrdp
  systemd:
    name: xrdp
    state: started
    daemon_reload: yes

- name: chcon
  shell: chcon --type=bin_t /usr/sbin/xrdp; chcon --type=bin_t /usr/sbin/xrdp-sesman

- name: enable xrdp
  systemd:
    name: firewalld
    enabled: yes
    daemon_reload: yes

- name: set ec2-user password
  user:
    name: "ec2-user"
    password: "{{ ec2-pass }}"
