#  <-- tasks file can include smaller files if warranted

# install EPEL
- name: check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: install EPEL repo.
  shell: yum install -y "{{ epel_repo_url }}"
  when: not epel_repofile_result.stat.exists

- name: import EPEL GPG key.
  shell: rpm --import "{{ epel_repo_gpg_key_url }}"
  when: not epel_repofile_result.stat.exists

# Server with GUI
- name: install the 'Server with GUI' package group
  yum:
    name: "@^Server with GUI"
    state: present
    skip_broken: yes

# Downgrade xorg-x11-server-Xorg
- name: downgrade xorg-x11-server-Xorg 1.19.3-11.el7_4.2
  shell: yum downgrade xorg-x11-server-Xorg-1.19.3-11.el7_4.2

- name: add exclude xorg-x11-server-Xorg,tigervnc-server to yum.conf
  lineinfile:
    dest: /etc/yum.conf
    state: present
    regexp: "^exclude=.*$"
    insertafter: EOF
    line: "exclude=xorg-x11-server-Xorg"

# install xrdp, tigervnc-server
- name: install the latest version of xrdp, tigervnc-server
  yum:
    name: "{{ item }}"
    state: latest
    skip_broken: yes
  with_items:
    - xrdp
    - tigervnc-server

# start xrdp
- name: start xrdp
  systemd:
    name: xrdp
    state: started
    daemon_reload: yes

- name: chcon
  shell: "chcon --type=bin_t {{ item }}" 
  with_items:
    - /usr/sbin/xrdp
    - /usr/sbin/xrdp-sesman
  
- name: enable xrdp
  systemd:
    name: xrdp
    enabled: yes
    daemon_reload: yes

# disabled firewalld
- name: disabled firewalld
  systemd:
    name: firewalld
    enabled: no
    daemon_reload: yes

- name: stop firewalld
  systemd:
    name: firewalld
    state: stopped
    daemon_reload: yes

# set User's Pass
- name: set ec2-user password
  user:
    name: "ec2-user"
    password: "{{ ec2_pass }}"
