#  <-- tasks file can include smaller files if warranted

- name: check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: install EPEL repo.
  shell: yum install -y "{{ epel_repo_url }}"
  when: not epel_repofile_result.stat.exists
 
#- name: install EPEL repo.
#  yum:
#    name: "{{ epel_repo_url }}"
#    state: present
#  register: result
#  when: not epel_repofile_result.stat.exists

- name: import EPEL GPG key.
  shell: rpm --import "{{ epel_repo_gpg_key_url }}"
  when: not epel_repofile_result.stat.exists

#- name: import EPEL GPG key.
#  rpm_key:
#    key: "{{ epel_repo_gpg_key_url }}"
#    state: present
#  when: not epel_repofile_result.stat.exists

- name: install the latest version of xrdp
  yum:
    name: xrdp
    state: latest
    skip_broken: yes

- name: install the 'Server with GUI' package group
  shell: yum groupinstall -y "Server with GUI" --skip-broken

- name: install the latest version of tigervnc-server
  yum:
    name: tigervnc-server
    state: latest
    skip_broken: yes

- name: disabled firewalld
  systemd:
    name: firewalld
    enabled: no
    daemon_reload: yes

- name: stop firewalld
  systemd:
    name: firewalld
    state: stopped
    daemon_reload: yes

- name: start xrdp
  systemd:
    name: xrdp
    state: started
    daemon_reload: yes

- name: set ec2-user password
  user:
    name: "ec2-user"
    password: "{{ '{{ec2-pass}}'|password_hash('sha512') }}"
